### PR TITLE
update ghoul transformation and script

### PR DESCRIPTION
**Pull request by TotoR115**
- the Script (ys0270.bcs) now handle the situation better
- yspotn01.itm: when drink, now set "Scripting State 3" to 1, allowing better control of the script
- ysghoul1.itm : set it to weapon, undispellable, remove portrait change - for the time beeing as there is no way back - add immunity to polymorph and disable buttons for casting, Thievings and innate ability to avoid shapeshift

### CODE REVIEW

**Comment by ALIENQuake** [comment]
Thanks!

**Comment by TotoR115** [comment]
Could you please make an EE install, juste in case ?

**Comment by ALIENQuake** [comment]
Sure!

**Comment by ALIENQuake** [comment]
@TotoR115 I've done EE installation and transformation works. Please note that even if the portrait change is currently gone, I've fixed a small variant of the ghoul portrait for EE installation simply by overwriting a small bmp with a large one. Hopefully, it will be back someday.

**Pull request merged**
